# Generated by Django 4.0.4 on 2022-05-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_questions_a_questions_b_questions_c_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_title',
        ),
    ]
