# Generated by Django 4.0.4 on 2022-05-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_thequiz_questionitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionitems',
            name='question_number',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
