# Generated by Django 4.0.4 on 2022-05-09 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_questionitems_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionitems',
            name='question_number',
            field=models.CharField(default='Question1', max_length=10),
        ),
        migrations.AlterField(
            model_name='thequiz',
            name='created_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 9, 11, 23, 52, 919961, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='thequiz',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
